### ISSUE TITLE
pantsel/konga version 0.8.5 fails to come up

### ISSUE THREAD

**Issue by mubeennakade** [pantsel/konga#106] opened 2017-09-24 10:16 UTC
Hi Pan,

With the pantsel/konga newly build tag ( latest or 0.8.5 ) application fails to come up.. Can you please check. Thanks.

Hook:api_health_checks:process() called
Hook:health_checks:process() called
Hook:user_events_hook:process() called
/app/node_modules/sails-hook-validation/index.js:34
        (_ || sails.util._)
         ^

ReferenceError: _ is not defined
    at patch (/app/node_modules/sails-hook-validation/index.js:34:10)
    at /app/node_modules/sails-hook-validation/index.js:101:21
    at /app/node_modules/sails/lib/app/private/after.js:91:14
    at /app/node_modules/async/lib/async.js:721:13
    at /app/node_modules/async/lib/async.js:52:16
    at done (/app/node_modules/async/lib/async.js:246:17)
    at /app/node_modules/async/lib/async.js:44:16
    at Sails.<anonymous> (/app/node_modules/async/lib/async.js:718:17)
    at Sails.<anonymous> (/app/node_modules/async/lib/async.js:167:37)
    at Sails.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Sails.emit (events.js:185:7)
    at Sails.emitter.emit (/app/node_modules/sails/lib/app/private/after.js:50:11)
    at /app/node_modules/sails/lib/app/private/loadHooks.js:103:15
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:52:16
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:550:17
    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:544:17
    at _arrayEach (/app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:543:13)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by pantsel** [comment] 2017-09-24 15:58
@mubeennakade ,
It turned out to be an external dependency issue. It is fixed with the latest commits.

**Comment by mingfang** [comment] 2017-09-24 16:11
confirming fix. thanks @pantsel

**Comment by mubeennakade** [comment] 2017-09-24 17:21
@pantsel 
Many Thanks for the needful.. Can you please also update 0.8.5 / 0.8.6 tag on docker hub  same as done for "latest" tag today..  when you get free time..

Once again Thank You.

**Comment by pantsel** [comment] 2017-09-24 17:50
Closing this since it's confirmed to be fixed

**Closed by pantsel** 2017-09-24 17:50 UTC
