### ISSUE TITLE
Excuse me, when will this version be supported kong 0.12.1 ??

### ISSUE THREAD

**Issue by taotao2014** [pantsel/konga#171] opened 2018-02-09 07:57 UTC
Excuse me, when will this version be supported kong 0.12.1 ??

**Comment by pantsel** [comment] 2018-02-09 08:10
Hello @taotao2014 ,

due to my workload I cannot follow  all of Kong's upgrades in "real time". 
Kong 0.12.1 will be supported, but I cannot give you an exact timeline.

**Comment by taotao2014** [comment] 2018-02-09 08:16
Thank you very much。look forward to....

**Comment by denis-fortin** [comment] 2018-02-13 10:35
Hi @taotao2014, I upgraded my Kong to 0.12.1 but I didn't notice any issue.

I am curious about what issue I can encounter. Do you know what could be affected when using Konga 0.9.0 with Kong 0.12.1 ?

Thanks!

**Comment by pantsel** [comment] 2018-02-13 10:43
@denis-fortin,

These are the possible breaking changes to the API (although I haven't tested to see if they actually affect usability).

1. The /upstreams/:upstream_name_or_id/targets/ has been updated to not show the full list of Targets anymore, but only the ones that are currently active in the load balancer. To retrieve the full history of Targets, you can now query /upstreams/:upstream_name_or_id/targets/all. The /upstreams/:upstream_name_or_id/targets/active endpoint has been removed.

2. The orderlist property of Upstreams has been removed.

Everything else should work just fine.

**Comment by hreidar** [comment] 2018-02-16 13:53
I can confirm that by stipping the "active" part off line 17 in /app/assets/js/app/upstreams/targets/edit-upstream-targets-controller.js I'm not seeing any errors so far using Konga 0.9.0 on top of Kong 0.12.1

My primarily usage is CRUD with apis, upstreams and targets.

**Comment by pantsel** [comment] 2018-03-02 21:26
@taotao2014 ,
Kong 0.12.x is now fully supported.
Closing this.

**Closed by pantsel** 2018-03-02 21:26 UTC

**Comment by taotao2014** [comment] 2018-03-06 02:14
@pantsel ,thank you very much,please accept our big  embrace.
