### ISSUE TITLE
Uncaught ReferenceError: angular is not defined

### ISSUE THREAD

**Issue by wsdflink** [pantsel/konga#124] opened 2017-10-28 15:14 UTC
Hi, after i installed konga and start with 'npm start', it shows the following error in console:

Uncaught ReferenceError: angular is not defined.

**Comment by pantsel** [comment] 2017-10-28 15:58
Hi @wsdflink ,

this is a duplicate of #117 , #84 , #79 , #53 .

The issue is also mentioned in the [FAQ](https://github.com/pantsel/konga#faq) section of README.md

**Closed by pantsel** 2017-10-28 15:58 UTC
