### ISSUE TITLE
Can't setup ACL blacklist/whitelist from the UI

### ISSUE THREAD

**Issue by Fabbbrrr** [pantsel/konga#18] opened 2017-01-06 04:38 UTC
Trying to setup the ACL plugin fails due to some UI bug that won't recognise the already created groups in the list. 

Using the api directly to create the config works as expected and once created like that, I can see the proper config in the UI.

Example:
blacklist not configured due the bug.
whitelist configured using the api.
![image](https://cloud.githubusercontent.com/assets/14916457/21707714/a8fade46-d425-11e6-9960-868009b0f6d6.png)

```
{
  "api_id": "f7caca8a-0f54-4d8f-8b97-8bc5c12f1256",
  "id": "a4f1f4b3-8968-4021-8b57-bcf4a9dc66fb",
  "created_at": 1483674535000,
  "enabled": true,
  "name": "acl",
  "config": {
    "blacklist": {},
    "whitelist": [
      "android"
    ]
  }
}
```

I've tried to use another dashboard solution and worked perfectly fine.

**Comment by pantsel** [comment] 2017-02-06 20:35
Maybe this is related to https://github.com/pantsel/konga/issues/7?

Try pressing enter after every word you wirte. There is a chip component handling array fields that is a little bit obscure. Maybe I'll change it at some point.

**Comment by pantsel** [comment] 2017-02-08 19:50
Closing this issue as probably duplicate of  #7 .

If that is not the case feel free to reopen with more details.

**Closed by pantsel** 2017-02-08 19:50 UTC
