### ISSUE TITLE
Adding apis consecutively pre-populates fields with previous entry

### ISSUE THREAD

**Issue by PauloGDPeixoto** [pantsel/konga#43] opened 2017-04-12 08:13 UTC
I noticed a strange issue in the latest (0.6.4, docker image) release:
I was adding three apis, and as soon as I clicked to add the second one, the form was already populated with the values of the previous api I submitted, as if I was editing it, but no, it added the api correctly and didn't touch the previous one. The same behaviour happened when I added a third api immediately afterwards, with the fields being populated with the second api's details.
The issue persists after changing to a different connection, but clears after a page refresh, although it will come back after adding an api.

**Comment by pantsel** [comment] 2017-04-12 09:24
@PauloGDPeixoto thanks.

I will check it out as soon as possible.

**Comment by pantsel** [comment] 2017-04-13 10:52
@PauloGDPeixoto, the issue is fixed on the latest push

**Closed** 2017-04-14 07:14 UTC
