### ISSUE TITLE
Kong UI to production

### ISSUE THREAD

**Issue by vautrinr** [pantsel/konga#8] opened 2016-11-30 16:59 UTC
Hello, 
I am currently trying to install konga to prod.
However, it seems to have an annoying problem: the url is localhost instead of my prod url, so i wont access from outside.

Regards,

Rémi

**Comment by pantsel** [comment] 2016-11-30 18:10
@vautrinr 

There is an example of front configuration file on following path.

<code>/frontend/config/config_example.json</code>
Just copy this to <code>/frontend/config/config.json</code> and make necessary changes to it.

<pre>
{
  "backendUrl": your-backend-url
  "frontend": {
    "ports": {
      "production": your-production-port,
      "development": 3001
    }
  }
}
</pre>

**Comment by vautrinr** [comment] 2016-12-01 07:44
`{
  "backendUrl": "http://xx.xx.xx.xx:xxxx",
  "frontend": {
    "ports": {
      "production": 3000,
      "development": 3001
    }
  }
}
`
Here it is !

However, it is not working. 

![image](https://cloud.githubusercontent.com/assets/7830183/20785783/4a7277ca-b7a2-11e6-9cd1-be82fa004a9f.png)


By the way, do you have any idea to run it as a deamon??

Thanks again mate,

Rémi

**Comment by pantsel** [comment] 2016-12-01 08:01
@vautrinr ,
I can't seem to be able to reproduce this problem. It is working fine on my side when i change the backendUrl in <code>config.json</code>.

Are you sure you have created a <code>config.json</code> file in <code>/frontend/config/</code> and you've made your changes there?

Are you trying to run Konga via <code>npm run production</code> or are you trying to run front and back separately?

**Comment by vautrinr** [comment] 2016-12-01 09:47
what should be my backend url format ?

**Comment by pantsel** [comment] 2016-12-01 09:49
http://{server_address}:{server_port}

ex. http://192.168.1.116:1337

**Comment by vautrinr** [comment] 2016-12-01 10:09
I run it via npm run production. 
I think the replacement is not working in my case...

**Comment by pantsel** [comment] 2016-12-01 10:12
I will check it later today and get back to you

**Comment by pantsel** [comment] 2016-12-02 21:49
@vautrinr 

I figured out what the problem is.

You have to change the <code>backendUrl</code> before building assets for production by running <code>gulp dist</code> in <code>/frontend</code>. The configuration variables are written in index.html at the time you build for production.  So you need to rerun <code>gulp dist</code> after you've changed your frontend configuration.

I'm on the works of building a CLI from which you will be able to specify the config variables every time you run Konga. 

<pre>
ex.  konga play --frontend-port=.... --backend-url=... --prod
</pre>

In the meantime, the above solution will work for you.

**Comment by pantsel** [comment] 2016-12-05 20:11
I'm assuming the above proposition  solves this issue for now. Closing it.

**Closed by pantsel** 2016-12-05 20:11 UTC
