### ISSUE TITLE
It is possible to disable user management and login

### ISSUE THREAD

**Issue by stijndehaes** [pantsel/konga#234] opened 2018-07-10 11:32 UTC
Hi,

After comparing this kong dashboard with https://github.com/PGBI/kong-dashboard, I find that this dashboard is cleaner and has more functionality like search.

However in my company we run every admin application behind google openid login. This means only our devs can access the admin applications. So we would like to be able to disable user management and the login, or automatically log in every user as an admin user. Is this currently possible?

Kind regards,
Stijn

**Comment by smklugherz** [comment] 2018-07-11 19:48
This looks like it might be an extension or variation on #230 .

**Comment by pantsel** [comment] 2018-07-12 13:16
@stijndehaes , as @smklugherz pointed out, the LDAP auth feature is what you need. 

It's in my plans to implement it, but i can't give you an exact roadmap.

**Comment by kwaxi** [comment] 2018-10-17 07:15
Having the ability to authenticate at Konga with OpenID Connect would be a great enhancement.

**Comment by sir-gon** [comment] 2018-11-19 21:31
I have another use case... I have Konga configured as another "API" in KONG itself, so... KONGA access is protected by a kong authentication plugin (api key, jwt, ...).

So, in my organization, we don't need user/passwords to manage Kong.
Is there a way to disable user authentication or some kind of "auto-login" for default admin account?

**Comment by pantsel** [comment] 2019-03-21 20:25
This feature will be introduced on the upcoming 0.14.4 version of Konga. Check out [CHANGELOG.md](https://github.com/pantsel/konga/blob/next/CHANGELOG.md) .
For now you can try it out using the [next](https://github.com/pantsel/konga/tree/next) branch or pulling `pantsel/konga:next` from docker hub.

**Closed by pantsel** 2019-03-21 20:25 UTC

**Comment by timduhenchanter** [comment] 2019-07-23 01:33
@pantsel I still do not see `NO_AUTH` being read in on the `next` branch?  Could we reopen this or am I missing something?

**Comment by pantsel** [comment] 2019-07-23 07:46
@timduhenchanter , if you run Konga 0.14.4-rc2 (next) passing the ENV variable `NO_AUTH=true`, Konga will start with no Authentication. Have you tried it? What happens?

**Comment by timduhenchanter** [comment] 2019-07-24 19:12
My apologies.  It was a stale Docker image.  `NO_AUTH` appears to be working as intended on `next`
