### ISSUE TITLE
Broken on Kong-v0.10.x

### ISSUE THREAD

**Issue by thecantero** [pantsel/konga#52] opened 2017-05-04 06:27 UTC
Checking at the SSL list is broken.

http://prntscr.com/f3wmrz

**Comment by pantsel** [comment] 2017-05-04 14:00
@thecantero , i'll get to it asap.

**Comment by pantsel** [comment] 2017-05-06 11:19
Hi @thecantero , the issue is addressed in the new release of Konga [v0.6.7](https://github.com/pantsel/konga/releases/tag/0.6.7).

Please confirm the fix.

Thank you for the feedback!

**Closed** 2017-05-15 15:00 UTC

**Comment by thecantero** [comment] 2017-05-22 08:26
Tested and fixed. Thanks
