### ISSUE TITLE
Certificate uploads fail

### ISSUE THREAD

**Issue by davemetocean** [pantsel/konga#145] opened 2017-11-30 23:01 UTC
Cert uploads are not working. Seems to be related to empty in incorrect node_id property for user.

This appears to fix the problem:
```
diff --git a/api/services/KongPluginService.js b/api/services/KongPluginService.js
index 1d62886..ab5a3b0 100644
--- a/api/services/KongPluginService.js
+++ b/api/services/KongPluginService.js
@@ -44,7 +44,7 @@ var KongPluginService = _.merge(_.cloneDeep(require('./KongService')), {
     },
 
     addCertificates : function(fds,req, res) {
-        var request = unirest.post(req.node_id + req.url.replace('/kong',''))
+        var request = unirest.post(req.connection.kong_admin_url + req.url.replace('/kong',''))
 
         if(req.kong_api_key) {
             request.headers({'apikey': req.kong_api_key})
```

**Comment by ciknight** [comment] 2017-12-04 07:28
I have the same problem.

**Comment by pantsel** [comment] 2017-12-05 07:15
@davemetocean , @ciknight ,

the issue is fixed on the latest commit.

**Closed** 2017-12-07 08:08 UTC
