### ISSUE TITLE
Snapshot not capturing upstreams 

### ISSUE THREAD

**Issue by borna75rz** [pantsel/konga#183] opened 2018-03-05 16:25 UTC
currently snapshots only capture APIs, plugins and consumers and i'm trying to take a full backup but my upstreams are missing in the snapshots. I am using konga version 0.8.8 and kong version 0.11.2.
the problem seems to be with a bug where it's trying to check the version but the version is 0.11.x. snapshots are working when snapshot kong version is 0.11.2 or 0.10.4. but it breaks with version 0.11.x.

**Comment by pantsel** [comment] 2018-03-05 18:54
@borna75rz ,
what version of Kong and Konga are you using?

**Comment by borna75rz** [comment] 2018-03-05 18:57
I am using konga version 0.8.8 and kong version 0.11.2.

**Comment by pantsel** [comment] 2018-03-05 19:01
@borna75rz, Konga is now in version [0.10.2](https://github.com/pantsel/konga/releases).

On my end, upstreams+targets apear in my snapshots with no problems, so I can't reproduce that issue.

Please, do upgrade and see if that fixes it.

I would suggest that you upgrade Kong to v0.12.x as well.

**Comment by borna75rz** [comment] 2018-03-06 09:30
thanks a lot! updating konga fixed the issue!

**Comment by pantsel** [comment] 2018-03-06 09:38
@borna75rz ,
glad to help.

Closing this.

**Closed by pantsel** 2018-03-06 09:38 UTC
