### ISSUE TITLE
Bottom panel connection chooser not refreshing connection

### ISSUE THREAD

**Issue by PauloGDPeixoto** [pantsel/konga#41] opened 2017-04-06 14:54 UTC
I had the opportunity to pull the new konga docker image to test the feature I suggested, and I noticed that it doesn't really switch the connection. The status bar displays the name of the new server, but the dashboard doesn't refresh, show the previous connection' stats, even after a hard refresh.

Also, not to be very picky, but would it be possible to make the list appear closer to the status bar? It would be nice to have it open near the place where we click for it to appear.

Anyway, great work, and thank you for taking the time to implement the features we suggest!

**Comment by pantsel** [comment] 2017-04-06 19:37
@PauloGDPeixoto , your're right. I've noticed that as well.
I'm currently working on a fix which requires a bit of work and refactoring. I will publish a new version this weekend so please, bare with me.

Thanks.

**Comment by pantsel** [comment] 2017-04-09 09:33
@PauloGDPeixoto . The issue is fixed in the new release.
https://github.com/pantsel/konga/releases/tag/0.6.4

**Comment by PauloGDPeixoto** [comment] 2017-04-10 08:29
I just pulled the new image from docker hub and I can confirm that it works, also the position for the selector is perfect! The only thing is that I need to refresh the page after selecting another connection, is that the expected behaviour?

**Comment by pantsel** [comment] 2017-04-13 10:52
@PauloGDPeixoto, the issue is fixed on the latest push

**Closed** 2017-04-14 07:14 UTC
